services:
    # Laravel Application Service
#    animatrix:
#        build:
#            context: .
#            dockerfile: Dockerfile
#        container_name: animatrix
#        volumes:
#            - ./:/var/www/html
#        ports:
#            - "8000:8000"
#        environment:
#            - DB_CONNECTION=mysql
#            - DB_HOST=mysql
#            - DB_PORT=3306
#            - DB_DATABASE=animatrix
#            - DB_USERNAME=laravel
#            - DB_PASSWORD=${DB_PASSWORD}
#        depends_on:
#            - mysql

    # MySQL Service
    animatrix-db:
        image: mysql:8.0
        container_name: animatrix-db
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=animatrix
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
